name: Release PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install release-please
        run: |
         curl -fsSL https://github.com/googleapis/release-please/releases/download/nightly-2025-05-24/release-please-cli-linux-x64.tar.gz | tar xz -C /usr/local/bin

      - name: Run release-please
        run: |
          release-please init --release-type go --target-branch main